<a href="https://colab.research.google.com/github/anitakumar/ml/blob/main/titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df['Travelalone']= np.where((df["SibSp"]+df["Parch"])>0,0,1).astype('uint8')

In [ ]:
df1 =df.drop(['PassengerId','Name','Ticket','Cabin','SibSp','Parch'],axis=1)

In [ ]:
df1.isna().sum()

Survived         0
Pclass           0
Sex              0
Age            177
Fare             0
Embarked         2
Travelalone      0
dtype: int64

In [ ]:
df['Age'].fillna(df1['Age'].median(skipna=True),inplace=True)

In [ ]:
df1['Age'].isna().sum()

177

In [ ]:
df1.head()

   Survived  Pclass     Sex   Age     Fare Embarked  Travelalone
0         0       3    male  22.0   7.2500        S            0
1         1       1  female  38.0  71.2833        C            0
2         1       3  female  26.0   7.9250        S            1
3         1       1  female  35.0  53.1000        S            0
4         0       3    male  35.0   8.0500        S            1

In [ ]:
df1.describe()

         Survived      Pclass         Age        Fare  Travelalone
count  891.000000  891.000000  714.000000  891.000000   891.000000
mean     0.383838    2.308642   29.699118   32.204208     0.602694
std      0.486592    0.836071   14.526497   49.693429     0.489615
min      0.000000    1.000000    0.420000    0.000000     0.000000
25%      0.000000    2.000000   20.125000    7.910400     0.000000
50%      0.000000    3.000000   28.000000   14.454200     1.000000
75%      1.000000    3.000000   38.000000   31.000000     1.000000
max      1.000000    3.000000   80.000000  512.329200     1.000000

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Survived     891 non-null    int64
 1   Pclass       891 non-null    int64
 2   Sex          891 non-null    object
 3   Age          714 non-null    float64
 4   Fare         891 non-null    float64
 5   Embarked     889 non-null    object
 6   Travelalone  891 non-null    uint8
dtypes: float64(2), int64(2), object(2), uint8(1)
memory usage: 42.8+ KB

In [ ]:
df1.isna().sum()

Survived         0
Pclass           0
Sex              0
Age            177
Fare             0
Embarked         2
Travelalone      0
dtype: int64

In [ ]:
df1.Age.fillna(df1.Age.median(skipna=True),inplace=True)

In [ ]:
df1.isna().sum()

Survived       0
Pclass         0
Sex            0
Age            0
Fare           0
Embarked       2
Travelalone    0
dtype: int64

In [ ]:
df_titanic=pd.get_dummies(df1, columns=['Pclass','Embarked','Sex'],drop_first=True)

In [ ]:
df_titanic.head()

,Survived,Age,Fare,Travelalone,Pclass_2,Pclass_3,Embarked_Q,Embarked_S,Sex_male
0,0,22.0,7.2500,0,False,True,False,True,True
1,1,38.0,71.2833,0,False,False,False,False,False
2,1,26.0,7.9250,1,False,True,False,True,False
3,1,35.0,53.1000,0,False,False,False,True,False
4,0,35.0,8.0500,1,False,True,False,True,True

Standardize the data

In [ ]:
df_titanic.head()

,Survived,Age,Fare,Travelalone,Pclass_2,Pclass_3,Embarked_Q,Embarked_S,Sex_male
0,0,22.0,7.2500,0,False,True,False,True,True
1,1,38.0,71.2833,0,False,False,False,False,False
2,1,26.0,7.9250,1,False,True,False,True,False
3,1,35.0,53.1000,0,False,False,False,True,False
4,0,35.0,8.0500,1,False,True,False,True,True

Sort out your target variables in this case survived

In [ ]:
x=df_titanic.drop(['Survived'],axis=1)

In [ ]:
x.head()

,Age,Fare,Travelalone,Pclass_2,Pclass_3,Embarked_Q,Embarked_S,Sex_male
0,22.0,7.2500,0,False,True,False,True,True
1,38.0,71.2833,0,False,False,False,False,False
2,26.0,7.9250,1,False,True,False,True,False
3,35.0,53.1000,0,False,False,False,True,False
4,35.0,8.0500,1,False,True,False,True,True

In [ ]:
y=df_titanic['Survived']

In [ ]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
transpose_MM= MinMaxScaler()
x_scaled=transpose_MM.fit_transform(x)

In [ ]:
pd.DataFrame(x_scaled)

            0         1    2    3    4    5    6    7
0    0.271174  0.014151  0.0  0.0  1.0  0.0  1.0  1.0
1    0.472229  0.139136  0.0  0.0  0.0  0.0  0.0  0.0
2    0.321438  0.015469  1.0  0.0  1.0  0.0  1.0  0.0
3    0.434531  0.103644  0.0  0.0  0.0  0.0  1.0  0.0
4    0.434531  0.015713  1.0  0.0  1.0  0.0  1.0  1.0
..        ...       ...  ...  ...  ...  ...  ...  ...
886  0.334004  0.025374  1.0  1.0  0.0  0.0  1.0  1.0
887  0.233476  0.058556  1.0  0.0  0.0  0.0  1.0  0.0
888  0.346569  0.045771  0.0  0.0  1.0  0.0  1.0  0.0
889  0.321438  0.058556  1.0  0.0  0.0  0.0  0.0  1.0
890  0.396833  0.015127  1.0  0.0  1.0  1.0  0.0  1.0

[891 rows x 8 columns]

The data is transformed o to 1

In [ ]:
transpose_SS= StandardScaler()
x_scaled=transpose_SS.fit_transform(x)

In [ ]:
pd.DataFrame(x_scaled)

,0,1,2,3,4,5,6,7
0,-0.565736,-0.502445,-1.231645,-0.510152,0.902587,-0.307562,0.619306,0.737695
1,0.663861,0.786845,-1.231645,-0.510152,-1.107926,-0.307562,-1.614710,-1.355574
2,-0.258337,-0.488854,0.811922,-0.510152,0.902587,-0.307562,0.619306,-1.355574
3,0.433312,0.420730,-1.231645,-0.510152,-1.107926,-0.307562,0.619306,-1.355574
4,0.433312,-0.486337,0.811922,-0.510152,0.902587,-0.307562,0.619306,0.737695
...,...,...,...,...,...,...,...,...
886,-0.181487,-0.386671,0.811922,1.960202,-1.107926,-0.307562,0.619306,0.737695
887,-0.796286,-0.044381,0.811922,-0.510152,-1.107926,-0.307562,0.619306,-1.355574
888,-0.104637,-0.176263,-1.231645,-0.510152,0.902587,-0.307562,0.619306,-1.355574
889,-0.258337,-0.044381,0.811922,-0.510152,-1.107926,-0.307562,-1.614710,0.737695
890,0.202762,-0.492378,0.811922,-0.510152,0.902587,3.251373,-1.614710,0.737695